version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: crud
      MYSQL_USER: crudadmin
      MYSQL_PASSWORD: Testlevelroot500
      MYSQL_ROOT_PASSWORD: Testlevelroot500
