version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:9000
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: crud
      DB_USERNAME: crudadmin
      DB_PASSWORD: Testlevelroot500
    volumes:
      - .:/var/www/html
  db:
    image: mysql:8.0
    ports:
      - 3307:3306  # Change the host port from 3306 to 3306
    environment:
      MYSQL_DATABASE: crud
      MYSQL_USER: crudadmin
      MYSQL_PASSWORD: Testlevelroot500
