version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: crud
      DB_USERNAME: crudadmin
      DB_PASSWORD: Testlevelroot500
    volumes:
      - .:/var/www/html
    #command: php -c /usr/local/etc/php/php.ini artisan serve --host=0.0.0.0 --port=8000    
  db:
    image: mysql:8.0
    ports:
      - 3307:3306  # Change the host port from 3306 to 3307 to avoid conflicts with a local MySQL server
    environment:
      MYSQL_DATABASE: crud
      MYSQL_USER: crudadmin
      MYSQL_PASSWORD: Testlevelroot500
      MYSQL_ROOT_PASSWORD: Testlevelroot500
